/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v4.1
processor: MK66FX1M0xxx18
package_id: MK66FX1M0VMD18
mcu_data: ksdk2_0
processor_version: 4.0.1
functionalGroups:
- name: BOARD_InitPeripherals
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * eDMA_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'eDMA_1'
- type: 'edma'
- mode: 'basic'
- type_id: 'edma_a23fca76a894e1bcdf9d01a687505ff9'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'false'
      - enableRoundRobinArbitration: 'false'
      - enableDebugMode: 'false'
    - edma_channels:
      - 0:
        - edma_channel:
          - channel_prefix_id: 'dummy'
          - eDMAn: '2'
          - eDMA_source: 'kDmaRequestMux0Disable'
          - enable_custom_name: 'false'
        - init_callback: 'false'
        - callback_function: ''
        - callback_user_data: ''
        - init_preemption: 'false'
        - preemption:
          - enableChannelPreemption: 'false'
          - enablePreemptAbility: 'false'
          - channelPriority: '0'
        - init_channel_link: 'false'
        - channel_link: 'kEDMA_LinkNone'
        - linkedChannel: '0'
        - init_bandwidth: 'false'
        - bandwidth: 'kEDMA_BandwidthStallNone'
        - init_interrupts: 'true'
        - channel_enabled_interrupts: 'kEDMA_MajorInterruptEnable'
        - interrupt_channel:
          - IRQn: 'DMA2_DMA18_IRQn'
          - enable_priority: 'false'
          - enable_custom_name: 'false'
        - tcd_pool_enable: 'false'
        - tcd_settings: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t eDMA_1_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = false,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = false
};

  /* Channel dummy global variables */
edma_handle_t eDMA_1_dummy_Handle;

void eDMA_1_init(void) {

  /* Channel dummy initialization */
  /* Set the source kDmaRequestMux0Disable request in the DMAMUX */
  DMAMUX_SetSource(EDMA_1_DMAMUX_BASEADDR, EDMA_1_DUMMY_DMA_CHANNEL, EDMA_1_DUMMY_DMA_REQUEST);
  /* Enable the 2 channel in the DMAMUX */
  DMAMUX_EnableChannel(EDMA_1_DMAMUX_BASEADDR, EDMA_1_DUMMY_DMA_CHANNEL);
  /* Create the eDMA eDMA_1_dummy_Handle handle */
  EDMA_CreateHandle(&eDMA_1_dummy_Handle, EDMA_1_DMA_BASEADDR, EDMA_1_DUMMY_DMA_CHANNEL);
  EDMA_EnableChannelInterrupts(EDMA_1_DMA_BASEADDR, EDMA_1_DUMMY_DMA_CHANNEL, kEDMA_MajorInterruptEnable);
  /* Enable interrupt DMA2_DMA18_IRQn request in the NVIC */
  EnableIRQ(EDMA_1_DMA_CH_INT_DONE_2_IRQN);
}

/***********************************************************************************************************************
 * WS28XX_BIT_TIME initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'WS28XX_BIT_TIME'
- type: 'ftm'
- mode: 'EdgeAligned'
- type_id: 'ftm_5e037045c21cf6f361184c371dbbbab2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FTM2'
- config_sets:
  - ftm_main_config:
    - ftm_config:
      - clockSource: 'kFTM_SystemClock'
      - clockSourceFreq: 'BOARD_BootClockRUN'
      - prescale: 'kFTM_Prescale_Divide_1'
      - timerFrequency: '719424'
      - bdmMode: 'kFTM_BdmMode_0'
      - pwmSyncMode: 'kFTM_SoftwareTrigger'
      - reloadPoints: ''
      - faultMode: 'kFTM_Fault_Disable'
      - faultFilterValue: '0'
      - deadTimePrescale: 'kFTM_Deadtime_Prescale_1'
      - deadTimeValue: '0'
      - extTriggers: ''
      - chnlInitState: ''
      - chnlPolarity: ''
      - useGlobalTimeBase: 'false'
    - timer_interrupts: ''
    - enable_irq: 'false'
    - ftm_interrupt:
      - IRQn: 'FTM2_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'false'
  - ftm_edge_aligned_mode:
    - ftm_edge_aligned_channels_config:
      - 0:
        - edge_aligned_mode: 'kFTM_EdgeAlignedPwm'
        - edge_aligned_pwm:
          - chnlNumber: 'kFTM_Chnl_0'
          - level: 'kFTM_HighTrue'
          - dutyCyclePercent: '27'
          - enable_chan_irq: 'true'
      - 1:
        - edge_aligned_mode: 'kFTM_EdgeAlignedPwm'
        - edge_aligned_pwm:
          - chnlNumber: 'kFTM_Chnl_1'
          - level: 'kFTM_NoPwmSignal'
          - dutyCyclePercent: '80'
          - enable_chan_irq: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ftm_config_t WS28XX_BIT_TIME_config = {
  .prescale = kFTM_Prescale_Divide_1,
  .bdmMode = kFTM_BdmMode_0,
  .pwmSyncMode = kFTM_SoftwareTrigger,
  .reloadPoints = 0,
  .faultMode = kFTM_Fault_Disable,
  .faultFilterValue = 0,
  .deadTimePrescale = kFTM_Deadtime_Prescale_1,
  .deadTimeValue = 0,
  .extTriggers = 0,
  .chnlInitState = 0,
  .chnlPolarity = 0,
  .useGlobalTimeBase = false
};

const ftm_chnl_pwm_signal_param_t WS28XX_BIT_TIME_pwmSignalParams[] = { 
  {
    .chnlNumber = kFTM_Chnl_0,
    .level = kFTM_HighTrue,
    .dutyCyclePercent = 27
  },
  {
    .chnlNumber = kFTM_Chnl_1,
    .level = kFTM_NoPwmSignal,
    .dutyCyclePercent = 80
  }
};

void WS28XX_BIT_TIME_init(void) {
  FTM_Init(WS28XX_BIT_TIME_PERIPHERAL, &WS28XX_BIT_TIME_config);
  FTM_SetupPwm(WS28XX_BIT_TIME_PERIPHERAL, WS28XX_BIT_TIME_pwmSignalParams, sizeof(WS28XX_BIT_TIME_pwmSignalParams) / sizeof(ftm_chnl_pwm_signal_param_t), kFTM_EdgeAlignedPwm, 719424U, WS28XX_BIT_TIME_CLOCK_SOURCE);
  FTM_EnableInterrupts(WS28XX_BIT_TIME_PERIPHERAL, kFTM_Chnl0InterruptEnable | kFTM_Chnl1InterruptEnable);
}

/***********************************************************************************************************************
 * GPIO_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO_1'
- type: 'gpio'
- mode: 'GPIO'
- type_id: 'gpio_f970a92e447fa4793838db25a2947ed7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIOA'
- config_sets:
  - fsl_gpio:
    - enable_irq: 'true'
    - port_interrupt:
      - IRQn: 'PORTA_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

void GPIO_1_init(void) {
  /* Make sure, the clock gate for port A is enabled (e. g. in pin_mux.c) */
  /* Enable interrupt PORTA_IRQn request in the NVIC */
  EnableIRQ(PORTA_IRQn);
}

/***********************************************************************************************************************
 * SPI_SDCARD initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SPI_SDCARD'
- type: 'dspi'
- mode: 'DSPI_Polling'
- type_id: 'dspi_305e5b03c593d065f61ded8061d15797'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'SPI1'
- config_sets:
  - fsl_dspi:
    - dspi_mode: 'kDSPI_Master'
    - clockSource: 'BusInterfaceClock'
    - clockSourceFreq: 'GetFreq'
    - dspi_master_config:
      - whichCtar: 'kDSPI_Ctar0'
      - ctarConfig:
        - baudRate: '400000'
        - bitsPerFrame: '8'
        - cpol: 'kDSPI_ClockPolarityActiveHigh'
        - cpha: 'kDSPI_ClockPhaseFirstEdge'
        - direction: 'kDSPI_MsbFirst'
        - pcsToSckDelayInNanoSec: '1000'
        - lastSckToPcsDelayInNanoSec: '1000'
        - betweenTransferDelayInNanoSec: '1000'
      - whichPcs: 'PCS1'
      - pcsActiveHighOrLow: 'kDSPI_PcsActiveLow'
      - enableContinuousSCK: 'false'
      - enableRxFifoOverWrite: 'false'
      - enableModifiedTimingFormat: 'false'
      - samplePoint: 'kDSPI_SckToSin0Clock'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const dspi_master_config_t SPI_SDCARD_config = {
  .whichCtar = kDSPI_Ctar0,
  .ctarConfig = {
    .baudRate = 400000,
    .bitsPerFrame = 8,
    .cpol = kDSPI_ClockPolarityActiveHigh,
    .cpha = kDSPI_ClockPhaseFirstEdge,
    .direction = kDSPI_MsbFirst,
    .pcsToSckDelayInNanoSec = 1000,
    .lastSckToPcsDelayInNanoSec = 1000,
    .betweenTransferDelayInNanoSec = 1000
  },
  .whichPcs = kDSPI_Pcs1,
  .pcsActiveHighOrLow = kDSPI_PcsActiveLow,
  .enableContinuousSCK = false,
  .enableRxFifoOverWrite = false,
  .enableModifiedTimingFormat = false,
  .samplePoint = kDSPI_SckToSin0Clock
};

void SPI_SDCARD_init(void) {
  /* Initialization function */
  DSPI_MasterInit(SPI_SDCARD_PERIPHERAL, &SPI_SDCARD_config, SPI_SDCARD_CLK_FREQ);
}

/***********************************************************************************************************************
 * Gen_timer_10k initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'Gen_timer_10k'
- type: 'ftm'
- mode: 'EdgeAligned'
- type_id: 'ftm_5e037045c21cf6f361184c371dbbbab2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FTM0'
- config_sets:
  - ftm_main_config:
    - ftm_config:
      - clockSource: 'kFTM_SystemClock'
      - clockSourceFreq: 'GetFreq'
      - prescale: 'kFTM_Prescale_Divide_1'
      - timerFrequency: '10000'
      - bdmMode: 'kFTM_BdmMode_0'
      - pwmSyncMode: 'kFTM_SoftwareTrigger'
      - reloadPoints: ''
      - faultMode: 'kFTM_Fault_Disable'
      - faultFilterValue: '0'
      - deadTimePrescale: 'kFTM_Deadtime_Prescale_1'
      - deadTimeValue: '0'
      - extTriggers: ''
      - chnlInitState: ''
      - chnlPolarity: ''
      - useGlobalTimeBase: 'false'
    - timer_interrupts: ''
    - enable_irq: 'true'
    - ftm_interrupt:
      - IRQn: 'FTM0_IRQn'
      - enable_priority: 'false'
      - enable_custom_name: 'false'
    - EnableTimerInInit: 'false'
  - ftm_edge_aligned_mode:
    - ftm_edge_aligned_channels_config:
      - 0:
        - edge_aligned_mode: 'kFTM_OutputCompare'
        - output_compare:
          - chnNumber: 'kFTM_Chnl_0'
          - output_compare_mode: 'kFTM_NoOutputSignal'
          - compareValue: '10'
          - enable_chan_irq: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ftm_config_t Gen_timer_10k_config = {
  .prescale = kFTM_Prescale_Divide_1,
  .bdmMode = kFTM_BdmMode_0,
  .pwmSyncMode = kFTM_SoftwareTrigger,
  .reloadPoints = 0,
  .faultMode = kFTM_Fault_Disable,
  .faultFilterValue = 0,
  .deadTimePrescale = kFTM_Deadtime_Prescale_1,
  .deadTimeValue = 0,
  .extTriggers = 0,
  .chnlInitState = 0,
  .chnlPolarity = 0,
  .useGlobalTimeBase = false
};

void Gen_timer_10k_init(void) {
  FTM_Init(GEN_TIMER_10K_PERIPHERAL, &Gen_timer_10k_config);
  FTM_SetupOutputCompare(GEN_TIMER_10K_PERIPHERAL, kFTM_Chnl_0, kFTM_NoOutputSignal, 10);
  FTM_SetTimerPeriod(GEN_TIMER_10K_PERIPHERAL, ((GEN_TIMER_10K_CLOCK_SOURCE/ (1U << (GEN_TIMER_10K_PERIPHERAL->SC & FTM_SC_PS_MASK))) / 10000) + 1);
  FTM_EnableInterrupts(GEN_TIMER_10K_PERIPHERAL, kFTM_Chnl0InterruptEnable);
  /* Enable interrupt FTM0_IRQn request in the NVIC */
  EnableIRQ(GEN_TIMER_10K_IRQN);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMAMUX_Init(EDMA_1_DMAMUX_BASEADDR);
  EDMA_Init(EDMA_1_DMA_BASEADDR, &eDMA_1_config);

  /* Initialize components */
  eDMA_1_init();
  WS28XX_BIT_TIME_init();
  GPIO_1_init();
  SPI_SDCARD_init();
  Gen_timer_10k_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
