/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MK66FX1M0xxx18
package_id: MK66FX1M0VMD18
mcu_data: ksdk2_0
processor_version: 4.0.1
pin_labels:
- {pin_num: A1, pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/SDRAM_CKE/FTM0_FLT1/SPI1_SIN, label: L7, identifier: L7}
- {pin_num: A2, pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT, label: L6, identifier: L6}
- {pin_num: A3, pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/SDRAM_A9/EWM_OUT_b/SPI1_SCK, label: L5, identifier: L5}
- {pin_num: A4, pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/SDRAM_A10/EWM_IN/SPI1_PCS0, label: L4, identifier: L4}
- {pin_num: B4, pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/SDRAM_A11/I2C0_SDA, label: L3, identifier: L3}
- {pin_num: C4, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/SDRAM_A12/I2C0_SCL, label: L2, identifier: L2}
- {pin_num: D4, pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, label: L1, identifier: L1}
- {pin_num: A5, pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, label: L0, identifier: L0}
- {pin_num: C3, pin_signal: PTD13/SPI2_SOUT/SDHC0_D5/FB_A21, label: ss_out, identifier: ss_out}
- {pin_num: B1, pin_signal: PTD12/SPI2_SCK/FTM3_FLT0/SDHC0_D4/FB_A20, label: ss_clk, identifier: ss_clk}
- {pin_num: C1, pin_signal: PTD15/SPI2_PCS1/SDHC0_D7/FB_A23, label: ss_clr, identifier: ss_clr}
- {pin_num: C9, pin_signal: PTD8/LLWU_P24/I2C0_SCL/LPUART0_RX/FB_A16, label: I2C_SCL, identifier: I2C_SCL}
- {pin_num: B9, pin_signal: PTD9/I2C0_SDA/LPUART0_TX/FB_A17, label: I2C_SDA, identifier: I2C_SDA}
- {pin_num: G10, pin_signal: ADC1_SE10/PTB4/ENET0_1588_TMR2/SDRAM_CS1_b/FTM1_FLT0, label: ACC_INT, identifier: ACC_INT}
- {pin_num: H10, pin_signal: ADC0_SE8/ADC1_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/SDRAM_CAS_b/FTM1_QD_PHA/TPM1_CH0, label: ser_clk}
- {pin_num: H9, pin_signal: ADC0_SE9/ADC1_SE9/TSI0_CH6/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/SDRAM_RAS_b/FTM1_QD_PHB/TPM1_CH1, label: ser_nclr}
- {pin_num: G11, pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/SDRAM_CS0_b/FTM0_FLT0, label: ser_out}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A5, peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, direction: OUTPUT, pull_select: no_init}
  - {pin_num: D4, peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, direction: OUTPUT, pull_select: no_init}
  - {pin_num: C4, peripheral: GPIOD, signal: 'GPIO, 2', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/SDRAM_A12/I2C0_SCL, direction: OUTPUT, pull_select: no_init}
  - {pin_num: B4, peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/SDRAM_A11/I2C0_SDA, direction: OUTPUT, pull_select: no_init}
  - {pin_num: A4, peripheral: GPIOD, signal: 'GPIO, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/SDRAM_A10/EWM_IN/SPI1_PCS0, direction: OUTPUT,
    pull_select: no_init}
  - {pin_num: A3, peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/SDRAM_A9/EWM_OUT_b/SPI1_SCK,
    direction: OUTPUT, pull_select: no_init}
  - {pin_num: A2, peripheral: GPIOD, signal: 'GPIO, 6', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT, direction: OUTPUT,
    pull_select: no_init}
  - {pin_num: A1, peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/SDRAM_CKE/FTM0_FLT1/SPI1_SIN, direction: OUTPUT, pull_select: no_init}
  - {pin_num: M12, peripheral: OSC, signal: EXTAL0, pin_signal: EXTAL0/PTA18/FTM0_FLT2/FTM_CLKIN0/TPM_CLKIN0}
  - {pin_num: M11, peripheral: OSC, signal: XTAL0, pin_signal: XTAL0/PTA19/FTM1_FLT0/FTM_CLKIN1/LPTMR0_ALT1/TPM_CLKIN1}
  - {pin_num: M7, peripheral: RTC, signal: XTAL32, pin_signal: XTAL32}
  - {pin_num: M6, peripheral: RTC, signal: EXTAL32, pin_signal: EXTAL32}
  - {pin_num: M9, peripheral: FTM2, signal: 'CH, 0', pin_signal: PTA10/LLWU_P22/FTM2_CH0/MII0_RXD2/FTM2_QD_PHA/TPM2_CH0/TRACE_D0}
  - {pin_num: C9, peripheral: I2C0, signal: SCL, pin_signal: PTD8/LLWU_P24/I2C0_SCL/LPUART0_RX/FB_A16}
  - {pin_num: B9, peripheral: I2C0, signal: SDA, pin_signal: PTD9/I2C0_SDA/LPUART0_TX/FB_A17}
  - {pin_num: G10, peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: ADC1_SE10/PTB4/ENET0_1588_TMR2/SDRAM_CS1_b/FTM1_FLT0, direction: INPUT, gpio_interrupt: kPORT_InterruptRisingEdge}
  - {pin_num: H10, peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE8/ADC1_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/FTM1_CH0/RMII0_MDIO/MII0_MDIO/SDRAM_CAS_b/FTM1_QD_PHA/TPM1_CH0,
    direction: OUTPUT}
  - {pin_num: H9, peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE9/ADC1_SE9/TSI0_CH6/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/SDRAM_RAS_b/FTM1_QD_PHB/TPM1_CH1,
    direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: G11, peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/UART0_CTS_b/UART0_COL_b/ENET0_1588_TMR1/SDRAM_CS0_b/FTM0_FLT0,
    direction: OUTPUT}
  - {pin_num: E3, peripheral: SPI1, signal: PCS0_SS, pin_signal: PTE4/LLWU_P2/SPI1_PCS0/UART3_TX/SDHC0_D3/TRACE_D0}
  - {pin_num: D1, peripheral: SPI1, signal: SCK, pin_signal: ADC1_SE6a/PTE2/LLWU_P1/SPI1_SCK/UART1_CTS_b/SDHC0_DCLK/TRACE_D2}
  - {pin_num: D2, peripheral: SPI1, signal: SIN, pin_signal: ADC1_SE5a/PTE1/LLWU_P0/SPI1_SOUT/UART1_RX/SDHC0_D0/TRACE_D3/I2C1_SCL/SPI1_SIN}
  - {pin_num: E4, peripheral: SPI1, signal: SOUT, pin_signal: ADC1_SE7a/PTE3/SPI1_SIN/UART1_RTS_b/SDHC0_CMD/TRACE_D1/SPI1_SOUT}
  - {pin_num: E11, peripheral: GPIOB, signal: 'GPIO, 11', pin_signal: ADC1_SE15/PTB11/SPI1_SCK/UART3_TX/FB_AD18/SDRAM_D18/FTM0_FLT2}
  - {pin_num: E12, peripheral: GPIOB, signal: 'GPIO, 10', pin_signal: ADC1_SE14/PTB10/SPI1_PCS0/UART3_RX/FB_AD19/SDRAM_D19/FTM0_FLT1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t gpiob_pinH10_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin H10)  */
    GPIO_PinInit(GPIOB, 0U, &gpiob_pinH10_config);

    gpio_pin_config_t gpiob_pinH9_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin H9)  */
    GPIO_PinInit(GPIOB, 1U, &gpiob_pinH9_config);

    gpio_pin_config_t gpiob_pinG11_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin G11)  */
    GPIO_PinInit(GPIOB, 3U, &gpiob_pinG11_config);

    gpio_pin_config_t ACC_INT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB4 (pin G10)  */
    GPIO_PinInit(BOARD_INITPINS_ACC_INT_GPIO, BOARD_INITPINS_ACC_INT_PIN, &ACC_INT_config);

    gpio_pin_config_t L0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD0 (pin A5)  */
    GPIO_PinInit(BOARD_INITPINS_L0_GPIO, BOARD_INITPINS_L0_PIN, &L0_config);

    gpio_pin_config_t L1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD1 (pin D4)  */
    GPIO_PinInit(BOARD_INITPINS_L1_GPIO, BOARD_INITPINS_L1_PIN, &L1_config);

    gpio_pin_config_t L2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD2 (pin C4)  */
    GPIO_PinInit(BOARD_INITPINS_L2_GPIO, BOARD_INITPINS_L2_PIN, &L2_config);

    gpio_pin_config_t L3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin B4)  */
    GPIO_PinInit(BOARD_INITPINS_L3_GPIO, BOARD_INITPINS_L3_PIN, &L3_config);

    gpio_pin_config_t L4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD4 (pin A4)  */
    GPIO_PinInit(BOARD_INITPINS_L4_GPIO, BOARD_INITPINS_L4_PIN, &L4_config);

    gpio_pin_config_t L5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD5 (pin A3)  */
    GPIO_PinInit(BOARD_INITPINS_L5_GPIO, BOARD_INITPINS_L5_PIN, &L5_config);

    gpio_pin_config_t L6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD6 (pin A2)  */
    GPIO_PinInit(BOARD_INITPINS_L6_GPIO, BOARD_INITPINS_L6_PIN, &L6_config);

    gpio_pin_config_t L7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD7 (pin A1)  */
    GPIO_PinInit(BOARD_INITPINS_L7_GPIO, BOARD_INITPINS_L7_PIN, &L7_config);

    /* PORTA10 (pin M9) is configured as FTM2_CH0 */
    PORT_SetPinMux(PORTA, 10U, kPORT_MuxAlt3);

    /* PORTA18 (pin M12) is configured as EXTAL0 */
    PORT_SetPinMux(PORTA, 18U, kPORT_PinDisabledOrAnalog);

    /* PORTA19 (pin M11) is configured as XTAL0 */
    PORT_SetPinMux(PORTA, 19U, kPORT_PinDisabledOrAnalog);

    /* PORTB0 (pin H10) is configured as PTB0 */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAsGpio);

    /* PORTB1 (pin H9) is configured as PTB1 */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAsGpio);

    /* PORTB10 (pin E12) is configured as PTB10 */
    PORT_SetPinMux(PORTB, 10U, kPORT_MuxAsGpio);

    /* PORTB11 (pin E11) is configured as PTB11 */
    PORT_SetPinMux(PORTB, 11U, kPORT_MuxAsGpio);

    /* PORTB3 (pin G11) is configured as PTB3 */
    PORT_SetPinMux(PORTB, 3U, kPORT_MuxAsGpio);

    /* PORTB4 (pin G10) is configured as PTB4 */
    PORT_SetPinMux(BOARD_INITPINS_ACC_INT_PORT, BOARD_INITPINS_ACC_INT_PIN, kPORT_MuxAsGpio);

    /* Interrupt configuration on PORTB4 (pin G10): Interrupt on rising edge */
    PORT_SetPinInterruptConfig(BOARD_INITPINS_ACC_INT_PORT, BOARD_INITPINS_ACC_INT_PIN, kPORT_InterruptRisingEdge);

    /* PORTD0 (pin A5) is configured as PTD0 */
    PORT_SetPinMux(BOARD_INITPINS_L0_PORT, BOARD_INITPINS_L0_PIN, kPORT_MuxAsGpio);

    /* PORTD1 (pin D4) is configured as PTD1 */
    PORT_SetPinMux(BOARD_INITPINS_L1_PORT, BOARD_INITPINS_L1_PIN, kPORT_MuxAsGpio);

    /* PORTD2 (pin C4) is configured as PTD2 */
    PORT_SetPinMux(BOARD_INITPINS_L2_PORT, BOARD_INITPINS_L2_PIN, kPORT_MuxAsGpio);

    /* PORTD3 (pin B4) is configured as PTD3 */
    PORT_SetPinMux(BOARD_INITPINS_L3_PORT, BOARD_INITPINS_L3_PIN, kPORT_MuxAsGpio);

    /* PORTD4 (pin A4) is configured as PTD4 */
    PORT_SetPinMux(BOARD_INITPINS_L4_PORT, BOARD_INITPINS_L4_PIN, kPORT_MuxAsGpio);

    /* PORTD5 (pin A3) is configured as PTD5 */
    PORT_SetPinMux(BOARD_INITPINS_L5_PORT, BOARD_INITPINS_L5_PIN, kPORT_MuxAsGpio);

    /* PORTD6 (pin A2) is configured as PTD6 */
    PORT_SetPinMux(BOARD_INITPINS_L6_PORT, BOARD_INITPINS_L6_PIN, kPORT_MuxAsGpio);

    /* PORTD7 (pin A1) is configured as PTD7 */
    PORT_SetPinMux(BOARD_INITPINS_L7_PORT, BOARD_INITPINS_L7_PIN, kPORT_MuxAsGpio);

    /* PORTD8 (pin C9) is configured as I2C0_SCL */
    PORT_SetPinMux(BOARD_INITPINS_I2C_SCL_PORT, BOARD_INITPINS_I2C_SCL_PIN, kPORT_MuxAlt2);

    /* PORTD9 (pin B9) is configured as I2C0_SDA */
    PORT_SetPinMux(BOARD_INITPINS_I2C_SDA_PORT, BOARD_INITPINS_I2C_SDA_PIN, kPORT_MuxAlt2);

    /* PORTE1 (pin D2) is configured as SPI1_SIN */
    PORT_SetPinMux(PORTE, 1U, kPORT_MuxAlt7);

    /* PORTE2 (pin D1) is configured as SPI1_SCK */
    PORT_SetPinMux(PORTE, 2U, kPORT_MuxAlt2);

    /* PORTE3 (pin E4) is configured as SPI1_SOUT */
    PORT_SetPinMux(PORTE, 3U, kPORT_MuxAlt7);

    /* PORTE4 (pin E3) is configured as SPI1_PCS0 */
    PORT_SetPinMux(PORTE, 4U, kPORT_MuxAlt2);

    SIM->SOPT4 = ((SIM->SOPT4 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT4_FTM2CH0SRC_MASK)))

                  /* FTM2 channel 0 input capture source select: FTM2_CH0 signal. */
                  | SIM_SOPT4_FTM2CH0SRC(SOPT4_FTM2CH0SRC_FTM));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
