/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT4_FTM2CH0SRC_FTM 0x00u /*!<@brief FTM2 channel 0 input capture source select: FTM2_CH0 signal */

/*! @name PORTD0 (coord A5), L0
  @{ */
#define BOARD_INITPINS_L0_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_L0_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_L0_PIN 0U     /*!<@brief PORTD pin index: 0 */
                                     /* @} */

/*! @name PORTD1 (coord D4), L1
  @{ */
#define BOARD_INITPINS_L1_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_L1_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_L1_PIN 1U     /*!<@brief PORTD pin index: 1 */
                                     /* @} */

/*! @name PORTD2 (coord C4), L2
  @{ */
#define BOARD_INITPINS_L2_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_L2_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_L2_PIN 2U     /*!<@brief PORTD pin index: 2 */
                                     /* @} */

/*! @name PORTD3 (coord B4), L3
  @{ */
#define BOARD_INITPINS_L3_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_L3_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_L3_PIN 3U     /*!<@brief PORTD pin index: 3 */
                                     /* @} */

/*! @name PORTD4 (coord A4), L4
  @{ */
#define BOARD_INITPINS_L4_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_L4_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_L4_PIN 4U     /*!<@brief PORTD pin index: 4 */
                                     /* @} */

/*! @name PORTD5 (coord A3), L5
  @{ */
#define BOARD_INITPINS_L5_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_L5_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_L5_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                     /* @} */

/*! @name PORTD6 (coord A2), L6
  @{ */
#define BOARD_INITPINS_L6_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_L6_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_L6_PIN 6U     /*!<@brief PORTD pin index: 6 */
                                     /* @} */

/*! @name PORTD7 (coord A1), L7
  @{ */
#define BOARD_INITPINS_L7_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_L7_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_L7_PIN 7U     /*!<@brief PORTD pin index: 7 */
                                     /* @} */

/*! @name PORTD8 (coord C9), I2C_SCL
  @{ */
#define BOARD_INITPINS_I2C_SCL_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_I2C_SCL_PIN 8U     /*!<@brief PORTD pin index: 8 */
                                          /* @} */

/*! @name PORTD9 (coord B9), I2C_SDA
  @{ */
#define BOARD_INITPINS_I2C_SDA_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_I2C_SDA_PIN 9U     /*!<@brief PORTD pin index: 9 */
                                          /* @} */

/*! @name PORTB4 (coord G10), ACC_INT
  @{ */
#define BOARD_INITPINS_ACC_INT_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_ACC_INT_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_ACC_INT_PIN 4U     /*!<@brief PORTB pin index: 4 */
                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
